### ISSUE TITLE
Load a trained model and continuing training don't work

### ISSUE THREAD

**Issue by FPerezHernandez92** [ziyangyeh/iMeshSegNet#1]
Thank you very much for the shared work.

I have tried to continue a training done with the train.py script. The problem is that when I set the ckpt to read the weights and continue the training I have to change in the function load_model of LitModule.py what is read from the ckpt since it was model_state_dict but what the ckpt contains is the state_dict. Also I need to change the strict flag to False so that it can read the model but start training with very low weights. What I can be doing wrong?

**Comment by ziyangyeh** [comment]
The function `load_model()` can only read the checkpoint file which contains the model's parameters only. In other words, `load_model()` read parameters from the output file with `torch.save(model.state_dict(), PATH)`, check [this](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

Typically, you should use pytorch-lightning's APIs to save and load checkpoints if you don't want to modify this repo too much. From `train.py` I have used `ModelCheckpoint()` to save the whole `LightningModule` but not only parameters. In `trainer.fit()` the key `ckpt_path` should point to the output file from `ModelCheckpoint()`, check [this](https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing_intermediate.html#which) and [this](https://pytorch-lightning.readthedocs.io/en/stable/common/checkpointing_basic.html#resume-training-state).

Moreover, If you really want to operate on parameters only, the easiest way I think is to get the parameters from ckpt file and find the key `model_state_dict`(not `state_dict` in lightning), then save it by using pytorch's `torch.save()`, then you can get a file that contains `state_dict` for further using.

**Comment by FPerezHernandez92** [comment]
Thank you very much for your reply.
I managed to start a training from an old checkpoint. What I had to do was to modify line 74 of the file `models/LitModule.py`: 
        `self.model.load_state_dict(ckpt["model_state_dict"], strict=True)`
And I rewrote it as follows:
        `self.model.load_state_dict(ckpt["state_dict"], strict=False)`

According to the answer you gave me, would this be correct? As I told you, I had to change the model_state_dict key as that information was not saved after training. Also, I have changed the strict as there were some inconsistencies.

**Comment by ziyangyeh** [comment]
Are you using iMeshSegNet or MeshSegNet?

**Comment by FPerezHernandez92** [comment]
MeshSegNet

**Comment by ziyangyeh** [comment]
The original purpose of `load_model()` is to load pretrained model from the official repo from [Tai-Hsien](https://github.com/Tai-Hsien) and the checkpoints' URL is [this](https://github.com/Tai-Hsien/MeshSegNet/tree/master/models).

I think you should create a new loader in `LitModule` class.
```
    def load_pramas_from_pl_ckpt(self, ckpt_path):
        tmp_model = self.load_from_checkpoint(ckpt_path)
        state_dict = tmp_model.model.state_dict()
        self.model.load_state_dict(state_dict, strict=True)
```
In the training script, you should call the above function after `LitModule` is instantiated.
```
module = LitModule(cfg)
module.load_pramas_from_pl_ckpt(ckpt_path=YOUR_CKPT_PATH)
```

**Comment by ziyangyeh** [comment]
> Thank you very much for your reply. I managed to start a training from an old checkpoint. What I had to do was to modify line 74 of the file `models/LitModule.py`: `self.model.load_state_dict(ckpt["model_state_dict"], strict=True)` And I rewrote it as follows: `self.model.load_state_dict(ckpt["state_dict"], strict=False)`
> 
> According to the answer you gave me, would this be correct? As I told you, I had to change the model_state_dict key as that information was not saved after training. Also, I have changed the strict as there were some inconsistencies.

There is no need to directly manipulate ckpt file which is saved by pytorch-lightning framework. Actually, it is a pickle, so using `pytorch_lightning.LightningModule.load_from_checkpoint()` to load ckpt file is highly needed.

**Comment by FPerezHernandez92** [comment]
Thank you very much, everything is working correctly now
