### ISSUE TITLE
网络识别效果不理想

### ISSUE THREAD

**Issue by koushiyu** [ziyangyeh/iMeshSegNet#2]
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/52336785/211764920-7fe511a2-392e-4c68-9f48-cb416ae3161a.png">
我用您的代码，训练的iMeshSegNet loss比较低的，但是识别的效果比较差，想请您指导一下，

**Comment by ziyangyeh** [comment]
Check my page to get my email address. Send me an email.
