### ISSUE TITLE
Alternative to the pygco function cut_from_graph

### ISSUE THREAD

**Issue by FPerezHernandez92** [ziyangyeh/iMeshSegNet#3]
Is there a possibility to use an alternative to the pygco library to avoid using the cut_from_graph function and get similar results?

**Comment by ziyangyeh** [comment]
Sure, you can replace whatever library you want to refine the final result.

**Comment by FPerezHernandez92** [comment]
Forgive my question, but, do you know of an option that could replace it?

**Comment by ziyangyeh** [comment]
I am definitely not an expert in graph cutting. Maybe you can investigate some SOTA multi-label optimisations with full implementations to get a better performance in refining labels.

**Comment by wangzhen5201314** [comment]
> Forgive my question, but, do you know of an option that could replace it?

HELLO I want to know how this program is going to work, I have VTP files, but where to enter the vtp path. There are several steps in the scripts folder What is the order in which I should run the code
